FROM python:3.11-slim

WORKDIR /app

COPY .env .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/register_ticket_api/ ./register_ticket_api/

CMD ["python", "-m", "register_ticket_api.main"]