version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ADMIN  # define in execution time
      POSTGRES_DB: event_access
    volumes:
      - ../src/db/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - event-net
  
networks:
  event-net:
    driver: bridge