FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/register_ticket_api/ ./register_ticket_api/

ENV PORT=8080

EXPOSE 8080

CMD ["python", "-m", "register_ticket_api.main"]