# CD pipeline for staging environment runs when PR gets merged with main branch

name: CD pipeline for staging environment

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  deploy-to-stg:
    uses: ./.github/workflows/cd-base.yml
    secrets: inherit # pragma: allowlist secret
    with:
      deployment_env: stg
      image_uri: ghcr.io/${{ github.repository_owner }}/register-ticket-api:${{ github.sha }}

  #promote-to-stg-passed:
    #needs: deploy-to-stg
    #runs-on: ubunt-latest
    #permissions:
      #packages: write
    
    #steps:
      #- name: Log in Github container registry
        #uses: docker/login-action@v3
        #with:
          #registry: ghcr.io
          #username: ${{ github.actor }}
          #password: ${{ secrets.GITHUB_TOKEN }}
      
      #- name: Tag as stg-passed
        #run: |
          #docker pull ghcr.io/${{ github.repository_owner }}/register-ticket-api:${{ github.sha }}
          #docker tag ghcr.io/${{ github.repository_owner }}/register-ticket-api:${{ github.sha }} \
                     #ghcr.io/${{ github.repository_owner }}/register-ticket-api:stg-passed
          #docker push ghcr.io/${{ github.repository_owner }}/register-ticket-api:stg-passed
